
# **cd in EEG_Practice file folder Using ELM & SVM train EEG_dataset**

In [0]:
from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/My\ Drive/Colab\ Notebooks

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive
/content/drive/My Drive/Colab Notebooks


In [0]:
cd EEG_Practice/

/content/drive/My Drive/Colab Notebooks/EEG_Practice


In [0]:
ls

data/  EEG_Practice.ipynb  elm.py  load_data.py  __pycache__/  random_layer.py


In [0]:
ls

EEG_Practice/  Tutorials/  VGG16_MNIST.ipynb  VGG16_Practice.ipynb


# **load EEG dataset**


In [0]:
import load_data

In [0]:

import load_data
# return DataSet class
data = load_data.read_data_sets(one_hot=False)

# get sample number
n_samples = data.train.num_examples

# get train data and labels by batch size
train_x, train_label = data.train.next_batch(n_samples)

# get test data
test_x = data.test.data

# get test labels
test_labels = data.test.labels


# **import elm based python  Using ELM train EEG**

In [0]:
import elm 

In [0]:
number_neruon= [100,200,500,800,1000]
for i in number_neruon:
    elmc = elm.ELMClassifier(n_hidden=i,activation_func='tanh')
    data = load_data.read_data_sets(one_hot=True)

    elmc.fit(train_x,train_label)
    Accuracy = elmc.score(test_x,test_labels)

    print("The number of ",i ,"neurons","Testing Accuracy is ",Accuracy)


The number of  100 neurons Testing Accuracy is  0.41167767685108725
The number of  200 neurons Testing Accuracy is  0.5377786952931461
The number of  500 neurons Testing Accuracy is  0.5494254060005506
The number of  800 neurons Testing Accuracy is  0.5781723093861822
The number of  1000 neurons Testing Accuracy is  0.5697254335260116


In [0]:
train_x.shape

(84420, 310)

#  **Using SVM with different kernel  to train EEG**

<font color='black' size=3 face="黑体">Second , beacuse the performance of ELM is not good, so i use  SVM Algorithm, And i use SVM with different kernel to see performance</font> 

In [0]:
import pandas as pd
import numpy as np

<font color='black' size=3 face="黑体">First i use 'linear' kernel to test this dataset </font>

In [0]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')

In [0]:
svclassifier.fit(train_x,train_label)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [0]:
y_pred = svclassifier.predict(test_x)

In [0]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(test_labels,y_pred))
print(classification_report(test_labels,y_pred))

[[ 9097  7792  1549]
 [ 3720 14622  1398]
 [ 2302  1133 16515]]
              precision    recall  f1-score   support

           0       0.60      0.49      0.54     18438
           1       0.62      0.74      0.68     19740
           2       0.85      0.83      0.84     19950

    accuracy                           0.69     58128
   macro avg       0.69      0.69      0.69     58128
weighted avg       0.69      0.69      0.69     58128



<font color='black' size=3 face="黑体">Using SVM with 'linear' kernel performace is : 69% 

</font>

<font color='black' size=3 face="黑体">
</font>

<font color='black' size=3 face="黑体">Second  i use another kernel 'poly' to test this dataset </font>

In [0]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='poly',degree=8)

In [0]:
svclassifier.fit(train_x,train_label)

/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=8, gamma='auto_deprecated',
    kernel='poly', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [0]:
y_pred = svclassifier.predict(test_x)

In [0]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(test_labels,y_pred))
print(classification_report(test_labels,y_pred))

[[ 8690  8269  1479]
 [ 2495 15894  1351]
 [ 2458   816 16676]]
              precision    recall  f1-score   support

           0       0.64      0.47      0.54     18438
           1       0.64      0.81      0.71     19740
           2       0.85      0.84      0.85     19950

    accuracy                           0.71     58128
   macro avg       0.71      0.70      0.70     58128
weighted avg       0.71      0.71      0.70     58128



<font color='black' size=3 face="黑体">Using SVM with 'poly' kernel performace is : 70% </font>

<font color='black' size=3 face="黑体">

</font>

<font color='black' size=3 face="黑体">Third i use another kernel 'rbf' to test this dataset </font>

In [0]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='rbf')

In [0]:
svclassifier.fit(train_x,train_label)

/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [0]:
y_pred = svclassifier.predict(test_x)

In [0]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(test_labels,y_pred))
print(classification_report(test_labels,y_pred))

[[10925  5714  1799]
 [ 1474 17657   609]
 [  685  1060 18205]]
              precision    recall  f1-score   support

           0       0.83      0.59      0.69     18438
           1       0.72      0.89      0.80     19740
           2       0.88      0.91      0.90     19950

    accuracy                           0.80     58128
   macro avg       0.81      0.80      0.80     58128
weighted avg       0.81      0.80      0.80     58128



<font color='black' size=3 face="黑体">Using SVM with 'rbf' kernel performace is : 80% 

</font>

# **Conclusion**

<font color='black' size=3 face="黑体">In this assigment , I use two algorithm to test this EEG , and especially,in terms of SVM I use several kernel to compare this performace </font>

<font color='black' size=3 face="黑体">For Fixed-ELM, the performace is just 59% for 1K neruons,so we can see that is not good and it is not my expection. Then, I use SVM ,for SVM I use several kernels : 'linear' 'poly' 'rbf' </font>

<font color='black' size=3 face="黑体">so compare those performace,I found that Using SVM with 'rbf' kernel the performace is best,it is 80% ,which is much better than ELM and other algorithms  </font>

# **Following Sections is another ELM version  Section**

<font color='black' size=3 face="黑体">this ELM version may has some problems,because it is very slow to train dataset even just 100 neruons

</font>

In [0]:
import numpy as np
# # from sklearn.datasets import load_iris  # 数据集
# import load_data
# from sklearn.model_selection import train_test_split  # 数据集的分割函数
# from sklearn.preprocessing import StandardScaler  # 数据预处理

# # 引入包含数据验证方法的包
# from sklearn import metrics

class SingeHiddenLayer(object):

    def __init__(self, X, y, num_hidden):
        self.data_x = np.atleast_2d(X)  # 判断输入训练集是否大于等于二维; 把x_train()取下来
        self.data_y = np.array(y).flatten()  # a.flatten()把a放在一维数组中，不写参数默认是“C”，也就是先行后列的方式，也有“F”先列后行的方式； 把 y_train取下来
        self.num_data = len(self.data_x)  # 训练数据个数
        self.num_feature = self.data_x.shape[
            1];  # shape[] 读取矩阵的长度，比如shape[0]就是读取矩阵第一维度的长度 (120行，4列，所以shape[0]==120,shapep[1]==4)
        self.num_hidden = num_hidden;  # 隐藏层节点个数

        # 随机生产权重（从-1，到1，生成（num_feature行,num_hidden列））
        self.w = np.random.uniform(-1, 1, (self.num_feature, self.num_hidden))

        # 随机生成偏置，一个隐藏层节点对应一个偏置
        for i in range(self.num_hidden):
            b = np.random.uniform(-0.6, 0.6, (1, self.num_hidden))
            self.first_b = b

        # 生成偏置矩阵，以隐藏层节点个数4为行，样本数120为列
        for i in range(self.num_data - 1):
            b = np.row_stack((b, self.first_b))  # row_stack 以叠加行的方式填充数组
        self.b = b

    # 定义sigmoid函数
    def sigmoid(self, x):
        return 1.0 / (1 + np.exp(-x))

    def train(self, x_train, y_train, classes):
        mul = np.dot(self.data_x, self.w)  # 输入乘以权重
        add = mul + self.b  # 加偏置
        H = self.sigmoid(add)  # 激活函数

        H_ = np.linalg.pinv(H)  # 求广义逆矩阵
        # print(type(H_.shape))

        # 将只有一列的Label矩阵转换，例如，iris的label中共有三个值，则转换为3列，以行为单位，label值对应位置标记为1，其它位置标记为0
        self.train_y = np.zeros((self.num_data, classes))  # 初始化一个120行，3列的全0矩阵
        for i in range(0, self.num_data):
            self.train_y[i, y_train[i]] = 1  # 对应位置标记为1

        self.out_w = np.dot(H_, self.train_y)  # 求输出权重

    def predict(self, x_test):
        self.t_data = np.atleast_2d(x_test)  # 测试数据集
        self.num_tdata = len(self.t_data)  # 测试集的样本数
        self.pred_Y = np.zeros((x_test.shape[0]))  # 初始化

        b = self.first_b

        # 扩充偏置矩阵，以隐藏层节点个数4为行，样本数30为列
        for i in range(self.num_tdata - 1):
            b = np.row_stack((b, self.first_b))  # 以叠加行的方式填充数组

        # 预测
        self.pred_Y = np.dot(self.sigmoid(np.dot(self.t_data, self.w) + b), self.out_w)

        # 取输出节点中值最大的类别作为预测值
        self.predy = []
        for i in self.pred_Y:
            L = i.tolist()
            self.predy.append(L.index(max(L)))

    def score(self, y_test):
        print("准确率：")
        # 使用准确率方法验证
        print(metrics.accuracy_score(y_true=y_test, y_pred=self.predy))


stdsc = StandardScaler()  # StandardScaler类,利用接口在训练集上计算均值和标准差，以便于在后续的测试集上进行相同的缩放
#data = read_data_sets(one_hot=False)
# data.train.labels.astype(int)
# data.test.labels.astype(int)

# data.train.labels=int(data.train.labels)
ELM = SingeHiddenLayer(train_x, train_label, 1000)  # 训练数据集，训练集的label，隐藏层节点个数
ELM.train(train_x, train_label, 3)
ELM.predict(test_x)
ELM.score(test_labels)


准确率：
0.46884461877236444
